name: Copy Garden to Main Site

on:
  push:
    branches:
      - main   # ou la branche de publication de votre garden

jobs:
  copy-garden:
    runs-on: ubuntu-latest

    steps:
      # 1. Clone le repo du garden (là où vous poussez votre source Eleventy)
      - name: Checkout garden repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 2. Installe les dépendances Node.js (obligatoire pour builder)
      - name: Install dependencies
        run: npm install

      # 3. Build le site statique (génère _site/)
      - name: Build the site
        run: npm run build

      # 4. Clone le repo principal qui sert le site github.io
      - name: Clone target (main site) repo
        uses: actions/checkout@v4
        with:
          repository: neybaf/gouez_f
          token: ${{ secrets.TARGET_REPO_TOKEN }}
          path: main_site

      # 5. Debug : liste les fichiers pour vérifier la présence de _site/
      - name: Debug: List files before copy
        run: |
          ls -l
          ls -l dist || echo "_site does not exist"
          ls -l main_site

      # 6. Copie le site généré dans le bon dossier du repo principal
      - name: Copy garden to main site repo
        run: |
          rm -rf main_site/garden
          mkdir -p main_site/garden
          cp -r dist/* main_site/garden/

      # 7. Commit et push les changements sur le repo principal
      - name: Commit & push to main site
        run: |
          cd main_site
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "GitHub Actions"
          git add garden
          git commit -m "Update digital garden from $GITHUB_SHA" || echo "No changes to commit"
          git push
